name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

permissions:
  actions: "write"
  contents: "write"
  id-token: "write"

jobs:
  call-build:
    uses: "./.github/workflows/ci-cookbook-copy.yaml"
    with:
      publish_releases: true
      publish_release_javadoc: false
      publish_modules_individually: true
      runtime_version: 25
      gradle_warning_mode: "summary"
    secrets:
      publishing_env_vars: |
        ORG_GRADLE_PROJECT_sonatypeUsername="${{ secrets.PAPERMC_SONATYPE_USERNAME }}"
        ORG_GRADLE_PROJECT_sonatypePassword="${{ secrets.PAPERMC_SONATYPE_PASSWORD }}"
        ORG_GRADLE_PROJECT_papermcSigningKey="${{ secrets.PAPERMC_GPG_KEY }}"
        ORG_GRADLE_PROJECT_papermcSigningPassword="${{ secrets.PAPERMC_GPG_PASSWORD }}"
